[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./deployment"}]

optimizer = true
optimizer_runs = 99999

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
tenderly = "${TENDERLY_RPC_URL}"
local = "${LOCAL_RPC_URL}"

[profile.mainnet]
cache_path = 'cache/mainnet'
broadcast = 'broadcast/mainnet'

[profile.arbitrum]
cache_path = 'cache/arbitrum'
broadcast = 'broadcast/arbitrum'

[profile.tenderly]
cache_path = 'cache/tenderly'
broadcast = 'broadcast/tenderly'

[profile.local]
cache_path = 'cache/local'
broadcast = 'broadcast/local'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
